# Generated by Django 4.2.4 on 2023-11-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='joinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=75)),
                ('LastName', models.CharField(max_length=75)),
                ('Email', models.EmailField(max_length=150)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Major', models.CharField(max_length=75)),
                ('Birthday', models.CharField(max_length=8)),
                ('City', models.CharField(max_length=100)),
                ('ShirtSize', models.CharField(max_length=2)),
            ],
        ),
    ]
